### ISSUE TITLE
Unable to create ticket with value as number

### ISSUE THREAD

**Issue by EricCrosson** [andygrunwald/go-jira#334]
## Describe the bug

What I did:

Try to create a ticket with a customfield value containing a number

What I expected to happen:

the yaml of a number (e.g. `value: 1`) would be parsed as a number when sent as an http request

What actually happened:

```
ERROR customfield_10115: Operation value must be a number
```

## To Reproduce

Not sure how to set up a field that only takes a number on the Jira admin side, but if you know of such a field, try to create a ticket and fill in a property that only takes a number

## Expected behavior

Number types can be sent to the Jira REST API without being coerced into a string

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* go-jira version (git tag or sha): not sure how to check? --version not a supported flag. installed from homebrew on macos today
* Go version (`go version`): go version go1.15.5 darwin/amd64
* Jira version: not sure how to check
* Jira type (cloud or on-premise): cloud
* Involved Jira plugins: none
* Operating System and version: macos big sur

## Additional context

How has this issue affected you? What are you trying to accomplish?

- can't fill out a property that every ticket needs when i create from go-jira

Providing context helps us come up with a solution that is most useful in the real world.

- thank you for taking a look! Great tool, can't wait to use it daily

**Comment by andygrunwald** [comment]
Hey @EricCrosson,
do you have a bit of code for us to reproduce the problem?

**Comment by EricCrosson** [comment]
Hi Andy,

well not really, I haven't written any code. I'm working with this `create` template (excerpt)

``` yaml
{{/* create template */ -}}
fields:
  project:
    key: {{ or .overrides.project "" }}
  issuetype:
    name: {{ or .overrides.issuetype "" }}{{if .meta.fields.priority.allowedValues}}
  priority: # Values: {{ range .meta.fields.priority.allowedValues }}{{.name}}, {{end}}
    name: {{ or .overrides.priority "" }}{{end}}{{if .meta.fields.reporter}}
  reporter:
    emailAddress: {{ or .overrides.reporter .overrides.login }}{{end}}{{if .meta.fields.assignee}}
  # story points
  # Waiting to support numbers: https://github.com/andygrunwald/go-jira/issues/334
  customfield_10115: # Values: 1, 2, 3, 5, 8, 13
    value: {{ or .overrides.story_points 1 }}
```

and using `jira create`. If I try to add the `customfield_10115` dict with `value: 1`, I get the `Operation value must be a number` error.
